---
apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: {{ .Values.service.name }}-tst
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.portTest }}
      nodePort: {{ .Values.service.nodePortTst }} # TODO make it dynamic

