replicaCount: 1
tag: 1
#namespace: default
service:
  type: NodePort
  name: micro-geo-svc
  nodePortTst: 30188
  nodePortPrd: 30183

ImageName: hhssaaffii/micro-geo

port: 8089
portTest: 8095

fullName: micro-geo

appName: micro-geo


host: hello-world-7.pvt

image: ##DOCKER_REGISTRY##/hhssaaffii/micro-geo

artifactory:
  name: artifactory

secretKeyRef:
  name: <db-name>

